name: BetterBan
version: 4.2.3
api: 5.0.0
main: supercrafter333\BetterBan\BetterBan
author: supercrafter333

permissions:
  BetterBan.admin:
    description: Bypass permission
    default: op
  BetterBan.editban.cmd:
    description: Command permission
    default: op
  BetterBan.banlog.cmd:
    description: Command permission
    default: op
  BetterBan.baninfo.cmd:
    description: Command permission
    default: op
  BetterBan.editipban.cmd:
    description: Command permission
    default: op
  BetterBan.betterban.cmd:
    description: Command permission
    default: op